name: 'hello world docker action'
description: 'some description'
inputs:
  who-to-greet:
  description: "name of the person"
  required: true
  default: 'world'
outputs: 
  time:
    description: 'time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-greet}}
