name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        type: environment
        required: true
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job triggered by : ${{ github.event_name }}"
          echo "Name of branch is ${{ github.ref }} and  repo is "
      - uses: actions/checkout@v3.3.0

      - name: File list
        run: |
          echo "The repo ${{ github.repository }} have below files: "
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: echo "Testing..."

  Production:
    runs-on: ubuntu-latest
    needs: [ Test, Load-Test ]
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run:  |
          echo "Step 1.."
          sleep 10
      - run:  |
          echo "Step 2.."
          sleep 10
      - run:  |
          echo "Step 3.."
          sleep 10
      - run:  |
          echo "Step 4.."
          sleep 10
      - run:  |
          echo "Step 5.."
          sleep 10



    
    
