name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: 
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job triggered by : ${{ github.event_name }}"
          echo "Name of branch is ${{ github.ref }} and  repo is "
      - uses: actions/checkout@v3.3.0

      - name: File list
        run: |
          echo "The repo ${{ github.repository }} have below files: "
          tree
    
