name: Build Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: run container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@myname'

      - name: time set in container for output
        run: echo "action greets at ${{ steps.hello-action.outputs.time }}"
  
